name: Generate Daily Sentences

on:
  schedule:
    # 毎日 00:00 UTC に実行
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sentences
        run: |
          #!/bin/bash
          set -euo pipefail

          # CEFR レベルの重み付け配列
          levels=("A1" "A2" "A2" "A2" "B1" "B1" "B1" "B1" "B2" "B2" "B2" "C1")

          # 生成する文の数
          NUM_SENTENCES=25

          for i in $(seq 1 $NUM_SENTENCES); do
            # ランダムに難易度を選択
            RANDOM_INDEX=$(( RANDOM % ${#levels[@]} ))
            DIFFICULTY=${levels[$RANDOM_INDEX]}

            echo "Generating sentence $i with difficulty: $DIFFICULTY"

            # Supabase Edge Function を呼び出し
            curl -X POST "${SUPABASE_URL}/functions/v1/generate-sentence" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
              -d "{\"difficulty\": \"${DIFFICULTY}\"}" || {
                echo "Failed to generate sentence $i. Continuing with next..."
                sleep 5
              }

            # レートリミット回避のため少し待機
            sleep 1
          done
